Repository wingled22/pagyeonjaFrontEnd, pull requests merged in 2024-04, with the labels that each got.

#167 Task#163
  src/components/Commuter/CommuterTable.jsx
  src/components/Commuter/CommuterUpdateModal.jsx
Labels: enhancement

#174 Fix invoked suspension date
  src/components/Commuter/CommuterTable.jsx
Labels: documentation

#186 fixed image container
  src/assets/css/CommuterDetails.css
  src/components/Commuter/CommuterDetails.jsx
Labels: documentation

#188 fixed image load path when missing for commuter
  src/components/Commuter/CommuterDetails.jsx
Labels: documentation

#177 removing some unwanted feature from rider update modal
  src/components/CommuterApproval/CommuterApprovalTablePage.jsx
  src/components/Rider/RiderDetailsModal.jsx
  src/routes/CommuterApprovalPage.jsx
Labels: enhancement

#196 Taskmj#191
  src/assets/css/CommuterApproval/CommuterApprovalTablePage.css
  src/components/CommuterApproval/CommuterApprovalTablePage.jsx
Labels: bug, enhancement, good first issue, Feature Enhancement

#206 Taskmj#200
  src/assets/css/CommuterApproval/CommuterApprovalTablePage.css
  src/components/CommuterApproval/CommuterApprovalTablePage.jsx
Labels: bug, enhancement

#252 Avoid the fetching of commuters after update
  package-lock.json
  src/components/Commuter/CommuterTable.jsx
  src/components/Commuter/CommuterUpdateModal.jsx
  src/routes/CommuterPage.jsx
Labels: enhancement

#255 fixed ride history commuter changes
  src/components/Commuter/CommuterAccordion.jsx
Labels: documentation

#267 cleaned unused functions and useEffects in riderdetails modal
  src/components/Rider/RiderAccordion.jsx
  src/components/Rider/RiderDetailsModal.jsx
Labels: enhancement

#269 Taskmj#249
  src/components/Rider/RiderTable.jsx
  src/components/Rider/RiderTopUpModal.jsx
Labels: enhancement

#272 fix accordion date and time
  src/components/Rider/RiderTopUpModal.jsx
Labels: enhancement

#271 263 separate accordion to list commuter
  src/components/Commuter/CommuterAccordion.jsx
  src/components/Commuter/CommuterAccordionList.jsx
  src/components/Commuter/CommuterDetails.jsx
  src/components/Commuter/CommuterDocumentViewerModal.jsx
  src/components/Commuter/CommuterTable.jsx
  src/components/Commuter/CommuterTableList.jsx
  src/components/Commuter/CommuterUpdateModal.jsx
Labels: Feature Enhancement

#276 fixing undefined value from rider toptuphistory status accordion
  src/components/Rider/RiderTopUpModal.jsx
Labels: Feature Enhancement

#281 278 cleaning up front end commuter
  src/components/Commuter/CommuterAccordion.jsx
  src/components/Commuter/CommuterDetails.jsx
  src/components/Commuter/CommuterDocumentViewerModal.jsx
  src/components/Commuter/CommuterSearch.jsx
  src/components/Commuter/CommuterSuspensionModal.jsx
  src/components/Commuter/CommuterTable.jsx
  src/components/Commuter/CommuterTableList.jsx
  src/components/Commuter/CommuterUpdateModal.jsx
Labels: Feature Enhancement

#280 Adjusted requirements for commuter approval
  src/components/CommuterApproval/CommuterApprovalRequirements.jsx
  src/components/Rider/RiderDocumentViewerModal.jsx
Labels: bug, Feature Enhancement

#282 Sprint4
  package-lock.json
  package.json
  src/assets/css/CommuterApproval/CommuterApprovalTablePage.css
  src/assets/css/CommuterDetails.css
  src/assets/css/CommuterSuspensionModal.css
  src/assets/css/RiderDocumentViewerModal.css
  src/assets/css/RiderTopUpModal.css
  src/assets/image/withHer.png
  src/components/Commuter/CommuterAccordion.jsx
  src/components/Commuter/CommuterAccordionList.jsx
  src/components/Commuter/CommuterDetails.jsx
  src/components/Commuter/CommuterDocumentViewerModal.jsx
  src/components/Commuter/CommuterSearch.jsx
  src/components/Commuter/CommuterSuspensionModal.jsx
  src/components/Commuter/CommuterTable.jsx
  src/components/Commuter/CommuterTableList.jsx
  src/components/Commuter/CommuterUpdateModal.jsx
  src/components/CommuterApproval/CommuterApprovalRequirements.jsx
  src/components/CommuterApproval/CommuterApprovalRequirementsCards.jsx
  src/components/CommuterApproval/CommuterApprovalSearchFilter.jsx
  src/components/CommuterApproval/CommuterApprovalTablePage.jsx
  src/components/Rider/RiderAccordion.jsx
  src/components/Rider/RiderDetailsModal.jsx
  src/components/Rider/RiderDocumentViewerModal.jsx
  src/components/Rider/RiderProfile.jsx
  src/components/Rider/RiderSuspensionModal.jsx
  src/components/Rider/RiderTable.jsx
  src/components/Rider/RiderTopUpModal.jsx
  src/components/Rider/RiderUpdateModal.jsx
  src/components/RiderApproval/ApprovalResponseConfirmationModal.jsx
  src/components/RiderApproval/Requirements.jsx
  src/components/RiderApproval/Rider_Approval_Table.jsx
  src/routes/CommuterApprovalPage.jsx
  src/routes/CommuterPage.jsx
  src/routes/RiderApprovalPage.jsx
  src/routes/RiderPage.jsx
Labels: Feature Enhancement
