Repository wingled22/pagyeonjaFrontEnd, pull requests merged in 2024-03, with the labels that each got.

#37 Adjusted the responsiveness of the homepage.
  src/assets/css/Charts.css
  src/assets/css/RiderPage.css
  src/components/Homepage/Charts.jsx
  src/routes/HomePage.jsx
Labels: bug

#39 4 rider approval dashboard
  package-lock.json
  src/App.jsx
  src/AppRouter.jsx
  src/assets/css/RiderApprovalDashboard.css
  src/assets/image/carlo.jpg
  src/assets/image/cliff.jpg
  src/assets/image/cs1.png
  src/assets/image/cs2.png
  src/assets/image/cs3.png
  src/assets/image/mp1.jpg
  src/assets/image/profilepng.png
  src/components/NavigationBar.jsx
  src/components/RiderApprovalComponents/Badge.jsx
  src/components/RiderApprovalComponents/FilterStatus.jsx
  src/components/RiderApprovalComponents/Requirements.jsx
  src/components/RiderApprovalComponents/RequirementsViewDriversLicense.jsx
  src/components/RiderApprovalComponents/RequirementsViewNBIClearance.jsx
  src/components/RiderApprovalComponents/RequirementsViewOrCr.jsx
  src/components/RiderApprovalComponents/Rider_Approval_Dashboard.jsx
  src/components/RiderApprovalComponents/Rider_Approval_Table.jsx
  src/components/RiderApprovalComponents/SearchBox.jsx
Labels: documentation

#58 Commuterdashboard
  src/assets/css/CommuterApproval/CommuterApprovalFilterStatus.css
  src/assets/css/CommuterApproval/CommuterApprovalSearchBox.css
  src/components/CommuterApproval/CommuterApprovalFilter.jsx
  src/components/CommuterApproval/CommuterApprovalSearchBox.jsx
  src/components/NavigationBar.jsx
  src/routes/CommuterApprovalPage.jsx
Labels: enhancement

#67 Commuterdashboard
  src/assets/css/CommuterApproval/CommuterApprovalTablePage.css
  src/assets/css/RiderApprovalDashboard.css
  src/components/CommuterApproval/CommuterApprovalBadge.jsx
  src/components/CommuterApproval/CommuterApprovalFilter.jsx
  src/components/CommuterApproval/CommuterApprovalTablePage.jsx
  src/components/NavigationBar.jsx
  src/components/RiderApprovalComponents/Rider_Approval_Dashboard.jsx
  src/components/RiderApprovalComponents/Rider_Approval_Table.jsx
  src/routes/CommuterApprovalPage.jsx
Labels: enhancement

#78 72 display riders to rider table
  src/components/Rider/RiderDocumentViewerModal.jsx
  src/components/Rider/RiderProfile.jsx
  src/components/Rider/RiderTable.jsx
  src/components/RiderProfile.jsx
  src/routes/RiderPage.jsx
Labels: enhancement

#89 fixing rider approval search and filter ui
  src/assets/css/RiderApproval/RiderApprovalDashboard.css
  src/assets/css/RiderPage.css
  src/components/RiderApproval/RiderApprovalSearchAndFilter.jsx
  src/components/RiderApproval/Rider_Approval_Table.jsx
  src/routes/CommuterApprovalPage.jsx
  src/routes/RiderApprovalPage.jsx
Labels: enhancement

#91 "Already made the search field functional."
  src/components/CommuterApproval/CommuterApprovalSearchFilter.jsx
  src/components/CommuterApproval/CommuterApprovalTablePage.jsx
  src/components/RiderApproval/RiderApprovalSearchAndFilter.jsx
Labels: enhancement

#98 87 display rider details in modal
  src/components/Rider/RiderDetailsModal.jsx
  src/components/Rider/RiderProfile.jsx
  src/components/Rider/RiderTable.jsx
Labels: enhancement

#102 added middle initial to rider's name
  src/components/Rider/RiderDetailsModal.jsx
Labels: enhancement

#104 Taskmj#92
  src/assets/css/CommuterApproval/CommuterApprovalRequirements.css
  src/assets/css/CommuterApproval/CommuterApprovalSearchAndFilter.css
  src/assets/css/CommuterApproval/CommuterApprovalTablePage.css
  src/assets/css/RiderApproval/RiderApprovalDashboard.css
  src/components/CommuterApproval/CommuterApprovalSearchFilter.jsx
  src/components/CommuterApproval/CommuterApprovalTablePage.jsx
  src/components/RiderApproval/RiderApprovalSearchAndFilter.jsx
  src/components/RiderApproval/Rider_Approval_Table.jsx
  src/routes/CommuterApprovalPage.jsx
  src/routes/RiderApprovalPage.jsx
Labels: enhancement

#106 display profile picture for rider profile dashboard
  src/assets/css/RiderPage.css
  src/components/Rider/RiderProfile.jsx
Labels: enhancement

#108 displayed the profile image for commuter dashboard
  src/assets/css/CommuterDetails.css
  src/components/Commuter/CommuterDetails.jsx
Labels: enhancement

#109 107 fixed the nullable profile path image in commuter
  src/assets/css/CommuterDetails.css
  src/components/Commuter/CommuterDetails.jsx
Labels: enhancement

#113 fixed the nullable profile path for displaying in rider dashboard
  src/assets/css/RiderPage.css
  src/components/Commuter/CommuterDetails.jsx
  src/components/Rider/RiderProfile.jsx
Labels: enhancement

#115 114 display profile image to rider modal details
  src/assets/css/RiderDetailsModal.css
  src/assets/css/RiderPage.css
  src/components/Commuter/CommuterDetails.jsx
  src/components/Rider/RiderDetailsModal.jsx
  src/components/Rider/RiderProfile.jsx
  src/components/Rider/RiderTable.jsx
  src/components/RiderApproval/Rider_Approval_Table.jsx
Labels: Feature Enhancement

#138 Filter status
  src/assets/css/RiderApproval/RiderApprovalDashboard.css
  src/components/CommuterApproval/CommuterApprovalSearchFilter.jsx
  src/components/CommuterApproval/CommuterApprovalTablePage.jsx
  src/components/RiderApproval/Requirements.jsx
  src/components/RiderApproval/RiderApprovalSearchAndFilter.jsx
  src/components/RiderApproval/Rider_Approval_Table.jsx
  src/routes/RiderApprovalPage.jsx
Labels: enhancement

#148 Rider app filter
  src/components/RiderApproval/RiderApprovalSearchAndFilter.jsx
  src/components/RiderApproval/Rider_Approval_Table.jsx
Labels: enhancement

#149 145 revoke suspension rider
  src/components/Rider/RiderSuspensionModal.jsx
  src/components/Rider/RiderTable.jsx
Labels: enhancement
